config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get 'messages', to: 'messages#index'
  get 'messages/:id', to: 'messages#show'
  # plans
  get 'my_plans', to: 'plans#my_plans', as: :my_plans
  resources :plans do
    resources :travels, only: %i[create]
    resources :messages, only: %i[new create]
  end
  # patch 'plans/:id/travels/', to: 'travels#rejected'
  # travels
  get 'my_requests', to: 'travels#my_requests', as: :my_requests
  get 'my_travels', to: 'travels#my_travels', as: :my_travels
  get 'my_reviews', to: 'reviews#my_reviews', as: :my_reviews

  # Reviews routes
  resources :travels, except: %i[new create] do
    resources :reviews, only: %i[new create]
  end

  resources :travels, only: [] do
    member do
      patch :mark_as_viewed
    end
  end

  resources :users do
    resources :reviews, only: %i[index show]
  end

  resources :reviews, only: %i[index edit update destroy]
end

app/models/travel.rb
class Travel < ApplicationRecord
  belongs_to :plan
  belongs_to :user

  has_many :reviews

  validates :user_id, presence: true, uniqueness: { scope: :plan_id }

  after_create_commit :broadcast_notifications_count, :broadcast_notifications

  def broadcast_notifications_count
    owner = self.plan.user
    new_requests_count = owner.plans.map(&:travels).flatten.select { |t| !t.viewed && t.status == "solicitado" }.count

    broadcast_prepend_to "counter_for_user_#{owner.id}",
                        target: "counter",
                        partial: "shared/notifications_count",
                        locals: { count: new_requests_count }
  end

  def broadcast_notifications
    owner = self.plan.user
    new_requests = owner.plans.map(&:travels).flatten.select { |t| !t.viewed && t.status == "solicitado"}

    broadcast_prepend_to "notifications_for_user_#{owner.id}",
                        target: "notifications",
                        partial: "shared/modal_notifications",
                        locals: { requests: new_requests }
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  before_action :query_params, only: %i[my_requests update]
  def my_requests
    if @plan_id.present?
      # Encuentra el plan por ID y obtén sus solicitudes; usa un array vacío si no se encuentra el plan
      @plan = @plan_id
      @my_requests = current_user.plans.find_by(id: @plan_id)&.travels || []
    else
      # Obtén todas las solicitudes de todos los planes del usuario
      @my_requests = current_user.plans.map(&:travels).flatten
    end
  end

  def create
    @travel = Travel.new
    @plan = Plan.find(params[:plan_id])
    @travel.user = current_user
    @travel.plan = @plan
    @ticket_available = accepted_travel_limit?(@plan)
    if @ticket_available == false
      @travel.save!
      owner = @travel.plan.user
      new_requests = owner.plans.map(&:travels).flatten.select { |t| !t.viewed && t.status == "solicitado"}

      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("counter_for_user_#{owner.id}", partial: "shared/notifications_count",
            locals: { count: new_requests.count  })
        end
        format.html do
          redirect_to my_travels_path and return
        end
      end

      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.append("notifications_for_user_##{owner.id}", partial: "shared/modal_notifications",
            locals: { requests: new_requests  })
        end
      end
    end

  end

  def my_travels
    @my_travels = Travel.where(user: current_user)
  end

  def update
    @plan = @plan_id
    @travel = Travel.find(params[:id])
    @travel.update(status: @status)
    redirect_to my_requests_path(query: { plan_id: @plan })
  end

  def destroy
    @travel = Travel.find(params[:id])
    if @travel
      flash[:notice] = ''
      @travel.destroy
      redirect_to my_travels_path, status: :see_other
    else
      render my_travels_path, status: :unprocessable_entity
    end
  end

  def mark_as_viewed
    travel = Travel.find(params[:id])
    travel.update(viewed: true)
    redirect_to my_requests_path(query: {plan_id:travel.plan.id} )
  end

  private

  def query_params
    @plan_id = params.dig(:query, :plan_id)
    @status = params.dig(:query, :status)
  end

  def travel_params
    params.require(:travel).permit(:status)
  end

  def accepted_travel_limit?(plan)
    num_acepted_travels = plan.travels.where(status: 'aceptado').count
    travelers_quantity = plan.travelers_quantity

    num_acepted_travels >= travelers_quantity
  end
end

app/views/travels/my_requests.html.erb
<div class="container mt-5" data-controller="travels-filters">
  <h1 class="bold mb-2 text-center text-md-start">Solicitudes recibidas</h1>
  <div id="filters" class="d-flex justify-content-center flex-wrap mb-3">
    <a href="" class="btn btn-outline-secondary my-4 mx-2 w-100" style="max-width: 150px;" data-action="click->travels-filters#filter"
      data-travels-filters-target="todos">
      <i class="bi bi-emoji-sunglasses"></i>
      Todos
    </a>
    <a href="" class="btn btn-outline-secondary my-4 mx-2 w-100" style="max-width: 150px;" data-action="click->travels-filters#filter"
      data-travels-filters-target="aceptado"> <i class="bi bi-emoji-heart-eyes"></i> Aceptado</a>
    <a href="" class="btn btn-outline-secondary my-4 mx-2 w-100" style="max-width: 150px;" data-action="click->travels-filters#filter"
      data-travels-filters-target="solicitado"><i class="bi bi-emoji-neutral me-1"></i>Solicitado</a>
    <a href="" class="btn btn-outline-secondary my-4 mx-2 w-100" style="max-width: 150px;" data-action="click->travels-filters#filter"
      data-travels-filters-target="rechazado"><i class="bi bi-emoji-tear"></i> Rechazado</a>
  </div>
  <div class="row mt-5">
    <% @my_requests.each do |r| %>
        <div class="col-12 col-md-6 col-lg-4 mb-4 travel-container">
          <div class="card profile-card h-100">
            <div class="card-header p-0">
              <%= image_tag "user_back.jpg", class: 'card-img-top img-fluid' %>
              <div class="profile-img">
                <% if r.user.photo.attached? %>
                  <%= cl_image_tag r.user.photo.key, height: 40, width: 40, crop: :fill, class: 'img-fluid rounded-circle' %>
                <% else %>
                  <%= image_tag "sinimagen.jpg", height: 40, width: 40, crop: :fill, class: 'img-fluid rounded-circle' %>
                <% end %>
              </div>
            </div>
            <div class="card-body text-center d-flex flex-column">
              <div class="d-flex justify-content-center align-items-center">
                <h5 class="card-title"><%= r.user.first_name%></h5>
                <%= link_to user_reviews_path(r.user.id), class: "icon-see ms-2" do %>
                  <i class="fa-regular fa-eye"></i>
                <% end %>
              </div>
              <p class="card-text"><%= r.user.occupation%></p>
              <div class="plan-details text-start flex-grow-1">
                <p>Plan solicitado:</p>
                <h5 class="card-title"><%= r.plan.name %></h5>
                <p class="description text-start"><%= r.plan.description %></p>
                <p class="card-text">
                  <i class="fa-regular fa-calendar me-2"></i> Fecha de partida: <%= r.plan.start_date.strftime('%d/%m/%Y') %>
                </p>
                <p class="card-text">
                  <i class="fa-solid fa-user-group me-2"></i> <%= r.plan.travelers_quantity %> viajeros
                </p>
                <p class="card-text">
                  <i class="fa-solid fa-hourglass-half me-2"></i>Estado: <span data-travels-filters-status-value=<%= r.status %>><%= r.status %></span>
                </p>
              </div>
              <% if r.status == "solicitado" %>
                <div class="d-flex justify-content-around container-btns">
                  <%= button_to 'Aceptar', travel_path(r, query: { plan_id:  @plan, status: 'aceptado'}), method: :patch, class: "btn btn-secondary btn-sm mb-2" %>
                  <%= button_to 'Rechazar', travel_path(r, query: { plan_id:  @plan, status: 'rechazado'}), method: :patch, class: "btn btn-secondary btn-sm mb-2" %>
                </div>
              <% end %>
              <% if r.status == "rechazado" %>
                <div class="d-flex justify-content-around container-btns">
                  <%= button_to 'Aceptar', travel_path(r, query: { plan_id:  @plan, status: 'aceptado'}), method: :patch, class: "btn btn-secondary btn-sm mb-2" %>
                </div>
              <% end %>
              <% if r.status == "aceptado" %>
                <div class="d-flex justify-content-around container-btns">
                  <%= button_to 'Rechazar', travel_path(r, query: { plan_id:  @plan, status: 'rechazado'}), method: :patch, class: "btn btn-secondary btn-sm mb-2" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/travels/my_travels.html.erb
<div id="myTravels" class="body container mt-5">
  <div class="header">
    <div class="banner">
      <video autoplay loop muted>
        <source src="<%= asset_path('my_travels.mp4') %>" type="video/mp4">
        Your browser does not support the video tag.
      </video>
      <div class="header-text container content d-flex justify-content-center text-center">
        <div>
          <h1 class="bolder">Mis solicitudes</h1>
        </div>
      </div>
    </div>
  </div>

  <% if flash[:notice] %>
    <div class="p-3 mb-2 rounded text-white <%= flash[:notice] ? 'bg-success' : 'bg-danger' %>">
      <strong>
        <span>
          <i class="fa-solid <%= flash[:notice] ? 'fa-check' : 'fa-exclamation-triangle' %>"></i>
          <%= "Solicitud eliminada con éxito." %>
        </span>
      </strong>
    </div>
  <% end %>

  <div class="row" data-controller="travels-filters">

    <div id="filters" class="d-flex justify-content-center flex-wrap mb-3">
      <a href="" class="btn btn-primary my-4 mx-2 w-100" style="max-width: 150px;" data-action="click->travels-filters#filter"
        data-travels-filters-target="todos">Todos</a>
      <a href="" class="btn btn-primary my-4 mx-2 w-100" style="max-width: 150px;" data-action="click->travels-filters#filter"
        data-travels-filters-target="aceptado">Aceptado</a>
      <a href="" class="btn btn-primary my-4 mx-2 w-100" style="max-width: 150px;" data-action="click->travels-filters#filter"
        data-travels-filters-target="solicitado">Solicitado</a>
      <a href="" class="btn btn-primary my-4 mx-2 w-100" style="max-width: 150px;" data-action="click->travels-filters#filter"
        data-travels-filters-target="rechazado">Rechazado</a>
    </div>

    <% @my_travels.each do |travel| %>
      <div class="col-12 col-md-6 d-flex align-items-stretch mb-4 travel-container">
        <div class="card plan-card travel-card shadow h-100">
          <div class="col-6">
            <% if travel.plan.photos.attached? %>
              <%= cl_image_tag travel.plan.photos.first.key, height: 300, width: 450, crop: :fill, class: 'img-fluid' %>
            <% else %>
              <%= image_tag "sinimagen.jpg", height: 300, width: 450, crop: :fill, class: 'img-fluid' %>
            <% end %>
          </div>
          <div class="col-6">
            <div class="card-body h-100 d-flex flex-column">
              <div class="flex-grow-1">
                <h5 class="card-title"><%= travel.plan.name %></h5>
                <p class="description text-start"><%= travel.plan.description %></p>
                <p class="card-text departament">
                  <i class="fa-solid fa-location-dot me-2"></i>Departamento: <%= travel.plan.departament %>
                </p>
                <p class="card-text departure-date">
                <i class="fa-regular fa-calendar me-2"></i> Fecha de partida: <%= travel.plan.start_date.strftime('%d/%m/%Y') %>
                </p>
                <p class="card-text travelers">
                  <i class="fa-solid fa-user-group me-2"></i> <%= travel.plan.travelers_quantity %> viajeros
                </p>
                <p class="card-text state">
                  <i class="fa-solid fa-hourglass-half me-2"></i>
                  Estado:
                  <span data-travels-filters-status-value=<%= travel.status %> class="badge ms-2 <%= travel.status == 'solicitado' ? 'text-bg-warning text-white' : travel.status == 'aceptado' ? 'text-bg-primary  text-white' : 'text-bg-danger  text-white' %>">
                    <%= travel.status.capitalize %>
                  </span>
                </p>
                <% if travel.status == 'aceptado' %>
                  <p class="card-text">
                    <i class="fa-solid fa-hourglass-half me-2"></i>
                    Reseña:
                    <span class="badge ms-2 <%= travel.reviews.exists? == false ? 'text-bg-warning text-white' : travel.reviews.exists? == true ? 'text-bg-primary text-white' : 'text-bg-danger text-white' %>">
                      <% if travel.reviews.exists? %>
                        <i class="fa-solid fa-check"></i>
                      <% else %>
                        <i class="fa-solid fa-xmark"></i>
                      <% end %>
                    </span>
                  </p>
                <% end %>
              </div>
              <div class="buttons d-flex justify-content-end">
                <%= link_to plan_path(travel.plan), class: "btn btn-primary me-2" do %>
                  <i class="fa-solid fa-eye"></i>
                <% end %>
                <% user_travel = travel.user_id %>
                <% if user_travel == current_user.id && travel.status == "aceptado" %>
                    <%= link_to new_plan_message_path(travel.plan), class: "btn btn-primary btn-reserve me-2" do %>
                      <i class="fa-regular fa-comment"></i>
                    <% end %>
                <% end %>
                <% if travel.status == 'aceptado' && travel.reviews.exists? %>
                  <%= link_to user_review_path(travel.user.id, travel.reviews[0].id), class: "btn btn-primary  me-2" do %>
                    <i class="fa-solid fa-star"></i>
                  <% end %>
                <% elsif travel.status == 'aceptado' %>
                  <%= link_to new_travel_review_path(travel.id), class: "btn btn-primary  me-2" do %>
                    <i class="fa-regular fa-star"></i>
                  <% end %>
                <% end %>
                <%= link_to travel_path(travel), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary" do %>
                      <i class="fa-solid fa-trash-can"></i>
                    <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>