config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get 'messages', to: 'messages#index'
  get 'messages/:id', to: 'messages#show'
  # plans
  get 'my_plans', to: 'plans#my_plans', as: :my_plans
  resources :plans do
    resources :travels, only: %i[create]
    resources :messages, only: %i[new create]
  end
  # patch 'plans/:id/travels/', to: 'travels#rejected'
  # travels
  get 'my_requests', to: 'travels#my_requests', as: :my_requests
  get 'my_travels', to: 'travels#my_travels', as: :my_travels
  get 'my_reviews', to: 'reviews#my_reviews', as: :my_reviews

  # Reviews routes
  resources :travels, except: %i[new create] do
    resources :reviews, only: %i[new create]
  end

  resources :travels, only: [] do
    member do
      patch :mark_as_viewed
    end
  end

  resources :users do
    resources :reviews, only: %i[index show]
  end

  resources :reviews, only: %i[index edit update destroy]
end

app/views/shared/_footer.html.erb
<footer class="footer py-4 bg-dark text-light">
  <div class="container">
    <div class="d-flex">
      <div class="mb-4 flex-grow-1">
        <div class="d-flex flex-column">
          <%= link_to "/", class: "navbar-brand" do %>
            <%= image_tag "logo_tripmate.png", height: "auto", width: 150%>
          <% end %>
          <small class="mt-2">“Conecta, comparte y explora con TripMate.”</small>
        </div>
      </div>
      <div class="mb-4">
        <h5 class="fw-bold">Síguenos en:</h5>
        <ul class="list-inline mt-2">
          <li class="list-inline-item">
            <a href="https://facebook.com" target="_blank" class="text-light"><i class="fa-brands fa-facebook-f"></i></a>
          </li>
          <li class="list-inline-item">
            <a href="https://twitter.com" target="_blank" class="text-light"><i class="fa-brands fa-twitter"></i></a>
          </li>
          <li class="list-inline-item">
            <a href="https://instagram.com" target="_blank" class="text-light"><i class="fa-brands fa-instagram"></i></a>
          </li>
        </ul>
      </div>
    </div>
    <div class="text-center">
      <small class="mb-0">&copy; <%= Time.current.year %> TripMate ❤ Todos los derechos reservados.</small>
    </div>
  </div>
</footer>

app/views/shared/_modal_notifications.html.erb
<div class="dropdown-menu dropdown-notifications dropdown-menu-right" aria-labelledby="notificationsDropdown" data-navbar-target="menu">
  <div class="header d-flex align-items-center">
    <p class="title flex-grow-1">Solicitudes de viajes</p>
    <%= link_to "Ver todos", my_requests_path, class: "nav-link" %>
  </div>
  <% requests.each do |request| %>
    <%= button_to mark_as_viewed_travel_path(request), method: :patch, remote: true, class: "dropdown-item" do %>
      <% if request.user.photo.attached? %>
        <%= cl_image_tag request.user.photo.key, class: "avatar", alt: "dropdown menu" %>
      <% else %>
        <%= image_tag "user.png", class: "avatar", alt: "dropdown menu" %>
      <% end %>
      <div>
        <p><%= request.user.first_name %> <%= request.user.last_name %> quiere unirse a tu plan:</p>
        <%= request.plan.name %>
      </div>
    <% end %>
  <% end %>
  <% if requests.empty? %>
    <div class="not-requests">
      <i class="bi bi-x-circle"></i>
      <p>No tienes nuevas solicitudes</p>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top bg-dark
    <%= 'd-none' if (controller_name == 'sessions' && action_name == 'new') || (controller_name == 'registrations' && action_name == 'new') %>
    <%= 'transparent' if(controller_name == 'pages')%>"
    data-controller="navbar" data-navbar-target="navbar">
  <div class="container">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "logo_tripmate.png", class: "logo" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Mensajes", messages_path, class: "nav-link me-4" %>
          </li>
          <li class="nav-item d-flex dropdown">
            <%= turbo_stream_from "counter_for_user_#{current_user.id}" %>
            <div id="counter">
              <%= render partial: "shared/notifications_count", locals: { count: @my_requests_not_viewed.count } %>
            </div>
            <%= turbo_stream_from "notifications_for_user_#{current_user.id}" %>
            <div id="notifications">
              <%= render partial: "shared/modal_notifications", locals: { requests: @my_requests_not_viewed } %>
            </div>
          </li>

          <li class="nav-item">
            <%= link_to "Todos los planes", plans_path, class: "btn btn-outline btn-sm me-2" %>
          </li>
           <li class="nav-item">
            <%= link_to "Crear plan", new_plan_path, class: "btn btn-sm me-3" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, height: 40, width: 40, crop: :fill, class: "img-fluid avatar", alt: "dropdown menu" %>
              <% else %>
                <%= image_tag "user.png", height: 40, width: 40, crop: :fill, class: "img-fluid avatar", alt: "dropdown menu" %>
              <% end %>
            </a>
            <div class="menu-user dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mi perfil", user_reviews_path(current_user.id), class: "dropdown-item" %>
              <%= link_to "Mis planes", my_plans_path(@plan), class: "dropdown-item" %>
              <%= link_to "Solicitudes enviadas", my_travels_path, class: "dropdown-item" %>
              <%= link_to "Cerrar sesión", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Inicia Sesión", new_user_session_path, class: "btn btn-md me-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "Registrate", new_registration_path(:user), class: "btn btn-outline  btn-md" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notifications_count.html.erb
<span id="notifications_count">
  <%= link_to "#", class: "notifications position-relative me-3 nav-link dropdown-toggle", data: { bs_toggle: "dropdown" }, id: "notificationsDropdown", aria: { expanded: "false" }, data: { action: "click->navbar#toggleDropdown" } do %>
    <i class="bi bi-bell-fill"></i>
    <% if count.to_i.positive? %>
      <span class="point position-absolute bg-danger border rounded-circle">
        <%= count %>
        <span class="visually-hidden">New alerts</span>
      </span>
    <% end %>
  <% end %>
</span>