config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get 'messages', to: 'messages#index'
  get 'messages/:id', to: 'messages#show'
  # plans
  get 'my_plans', to: 'plans#my_plans', as: :my_plans
  resources :plans do
    resources :travels, only: %i[create]
    resources :messages, only: %i[new create]
  end
  # patch 'plans/:id/travels/', to: 'travels#rejected'
  # travels
  get 'my_requests', to: 'travels#my_requests', as: :my_requests
  get 'my_travels', to: 'travels#my_travels', as: :my_travels
  get 'my_reviews', to: 'reviews#my_reviews', as: :my_reviews

  # Reviews routes
  resources :travels, except: %i[new create] do
    resources :reviews, only: %i[new create]
  end

  resources :travels, only: [] do
    member do
      patch :mark_as_viewed
    end
  end

  resources :users do
    resources :reviews, only: %i[index show]
  end

  resources :reviews, only: %i[index edit update destroy]
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_travel, only: %i[create new]
  before_action :set_user, only: %i[index show]
  before_action :set_review, only: %i[show edit update destroy]

  def show
    @current_user = current_user
  end

  def index
    # reviews of a user
    if @user.present?
      @reviews = @user.plans.map(&:travels).flatten.map(&:reviews).flatten
      @reviews = @reviews.sort_by(&:created_at).reverse

      total_reviews = @reviews.size
      total_rating = @reviews.sum(&:rating)
      @rating = total_reviews > 0 ? (total_rating.to_f / total_reviews).round(2) : 0

      @plans = @user.plans.limit(3)
    else
      @reviews = Review.none
    end
  end

  def my_reviews
    # reviews made by current user
    @reviews = Review.where(user_id: current_user)
    @user = current_user
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @review.travel_id = @travel.id
    if @review.save!
      flash[:notice] = ''
      redirect_to user_review_path(@review.user_id, @review.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    flash[:notice] = ''
    @review.update(review_params)
    flash[:notice] = "Reseña actualizada exitosamente."
    redirect_to my_reviews_path
  end

  def destroy
    if @review
      flash[:notice] = ''
      @review.destroy
      flash[:notice] = "Reseña eliminada exitosamente."
      redirect_to my_reviews_path, status: :see_other
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :comment, :rating)
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_travel
    @travel = Travel.find(params[:travel_id])
  end
end

app/views/reviews/_card_travel.html.erb
<div class="travel card plan-card shadow h-100">
  <% if travel.plan.photos.attached? %>
    <%= cl_image_tag travel.plan.photos.first.key, height: 300, width: 450, crop: :fill, class: 'img-fluid' %>
  <% else %>
    <%= image_tag "sinimagen.jpg", height: 300, width: 450, crop: :fill, class: 'img-fluid' %>
  <% end %>
  <div class="card-body d-flex flex-column justify-content-between">
    <h5 class="card-title"><%= travel.plan.name %></h5>
    <p class="description text-start"><%= travel.plan.description %></p>
    <p class="card-text">
      <i class="fa-regular fa-clock me-2"></i>
      <%= (travel.plan.end_date - travel.plan.start_date).to_i %> Noches,
      <%= (travel.plan.end_date - travel.plan.start_date).to_i + 1 %> Días
    </p>
    <p class="card-text">
    <i class="fa-regular fa-calendar me-2"></i> Fecha de partida: <%= travel.plan.start_date.strftime('%d/%m/%Y') %>
    </p>
    <p class="card-text">
      <i class="fa-solid fa-user-group me-2"></i> <%= travel.plan.travelers_quantity %> viajeros
    </p>
    <div class="card-text flex-column align-items-start justify-content-center">
      <p class="my-2"><strong>Creador del viaje</strong></p>
      <div class="d-flex card-user">
        <% if travel.plan.user.photo.attached? %>
          <%= cl_image_tag travel.plan.user.photo.key, height: 48, width: 48, crop: :fill, class: 'avatar img-fluid rounded-circle' %>
        <% else %>
          <%= image_tag "sinimagen.jpg", height: 48, width: 48, crop: :fill, class: 'avatar img-fluid rounded-circle' %>
        <% end %>
        <div>
          <p><strong><%= travel.plan.user.first_name %></strong></p>
          <p class="traveler">Viajera</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [travel, review] do |f| %>
  <%= f.error_notification %>
  <%= f.input :title, label: 'Titulo de la reseña', required: true, input_html: { class: 'form-control required-input' } %>
  <%= f.input :comment, label: 'Comentario', as: :text, required: true, input_html: { class: 'form-control required-input rich-editor', 'data-new-review-target': 'editor', 'data-richeditor': 'rich-editor' } %>
  <%= f.input :rating, collection: (1..5).to_a, label: "Califica a el usuario", input_html: {data: {controller: "star-rating"}} %>
  <div class="text-end"><%= f.submit 'Crear', class: 'btn btn-primary btn-md' %></div>
<% end %>

app/views/reviews/edit.html.erb
<div class="container mt-5 body" data-controller="new-review">
  <h1>Edit</h1>
  <%= simple_form_for [@review] do |f| %>
    <div data-controller="new-review">
      <%= f.error_notification %>
      <%= f.input :title, label: 'Titulo de la reseña', required: true, input_html: { class: 'form-control required-input' } %>
      <%= f.input :comment, label: 'Comentario', as: :text, required: true, input_html: { class: 'form-control required-input rich-editor', 'data-new-review-target': 'editor', 'data-richeditor': 'rich-editor' } %>
      <%= f.input :rating, collection: (1..5).to_a, label: "Califica a el usuario", input_html: {data: {controller: "star-rating"}} %>
      <div class="text-end"><%= f.submit 'Guardar', class: 'btn btn-primary btn-md' %></div>
    </div>
  <% end %>
</div>

app/views/reviews/index.html.erb
<div id="myProfile" class="container body mt-5" data-controller="profile">
  <div class="container-info d-flex align-items-start">
    <div class="card info-profile d-flex flex-row">
      <div class="image">
        <% if @user.photo.attached? %>
          <%= cl_image_tag @user.photo.key, height: 104, width: 104, crop: :fill, class: 'img-fluid' %>
        <% else %>
          <%= image_tag "sinimagen.jpg", height: 104, width: 104, crop: :fill, class: 'img-fluid' %>
        <% end %>
        <p class="name"><%= "#{@user.first_name} #{@user.last_name}" %></p>
        <p>TripMater</p>
      </div>
      <div class="d-flex flex-column details">
        <div class="detail">
          <p><%=@reviews.count%><p>
          <small>Evaluaciones</small>
        </div>
        <div class="detail">
          <p><%=@rating%><p>
          <small>Calificación</small>
        </div>
        <div class="detail">
          <% days = (Time.zone.now.to_date - @user.created_at.to_date).to_i %>
          <p><%= days %></p>
          <small>días como viajero</small>
        </div>
      </div>
    </div>
    <div class="user-info">
      <div class="d-flex align-items-start">
        <p class="name">Acerca de <%= "#{@user.first_name}" %></p>
        <% if @user == current_user %>
          <%= link_to edit_user_registration_path, class: "btn btn-primary mt-2 ms-3" do %>
            <i class="fa-solid fa-pen-to-square"></i>
          <% end %>
        <% end %>
      </div>
      <div class="row">
        <p class="info col-6">
          <% age = ((Time.zone.now - @user.birth_date.to_time) / 1.year.seconds).floor %>
          <i class="bi bi-cake2"></i>
          Tiene <%= age %> años
        </p>
        <p class="info col-6">
          <i class="bi bi-briefcase"></i>
          Me dedico a: <%= @user.occupation%>
        </p>
        <p class="info col-6">
          <% match_data = @user.address.match(/[0-9]+\s*,?\s*(.*)$/) %>
          <% public_address = match_data ? match_data[1].strip : '' %>
          <i class="bi bi-geo-alt"></i>Vive en <%= public_address %>
        </p>
        <%# <p class="description">Descripción</p> %>
      </div>
      <hr/>
      <div class="reviews">
        <p class="title">Lo que dicen los tripmater sobre <%= @user.first_name %></p>
        <% if @reviews.any? %>
          <% if @reviews.count > 2%>
            <div class="carousel-reviews splide h-100">
              <div class="splide__track h-100">
                <ul class="splide__list">
                  <% @reviews.each do |review| %>
                    <div class="splide__slide">
                      <div class="card h-100 d-flex">
                        <div class="flex-grow-1">
                          <p class="title"><%=review.title%></p>
                          <div class="description d-flex"><i class="fa-solid fa-quote-left me-2"></i><%=raw review.comment%></div>
                        </div>
                        <div class="d-flex align-items-start">
                          <% if review.user.photo.attached? %>
                            <%= cl_image_tag review.user.photo.key, height: 48, width: 48, crop: :fill, class: 'img-fluid rounded-circle' %>
                          <% else %>
                            <%= image_tag "sinimagen.jpg", height: 48, width: 48, crop: :fill, class: 'img-fluid rounded-circle' %>
                          <% end %>
                          <div class="user">
                            <p class="user-name"><%= "#{review.user.first_name} #{review.user.last_name}" %></p>
                            <p class="stars">
                              <span>
                                <% review.rating.times do %>
                                  <i class="fa-solid fa-star"></i>
                                <% end %>
                                <% (5 - review.rating).times do %>
                                  <i class="fa-regular fa-star"></i>
                                <% end %>
                              </span>
                            </p>
                            <p><%= review.created_at.strftime('%d/%m/%Y') %></p>
                          </div>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </ul>
              </div>
            </div>
          <%else%>
          <div class="d-flex gap-2">
            <% @reviews.each do |review| %>
                <div class="card w-50 d-flex shadow-sm">
                  <div class="flex-grow-1">
                    <p class="title"><%=review.title%></p>
                    <div class="description d-flex"><i class="fa-solid fa-quote-left me-2"></i> <%=raw review.comment%></div>
                  </div>
                  <div class="d-flex align-items-start">
                    <% if review.user.photo.attached? %>
                      <%= cl_image_tag review.user.photo.key, height: 48, width: 48, crop: :fill, class: 'img-fluid rounded-circle' %>
                    <% else %>
                      <%= image_tag "sinimagen.jpg", height: 48, width: 48, crop: :fill, class: 'img-fluid rounded-circle' %>
                    <% end %>
                    <div class="user">
                      <p class="user-name"><%= "#{review.user.first_name} #{review.user.last_name}" %></p>
                      <p class="stars">
                        <span>
                          <% review.rating.times do %>
                            <i class="fa-solid fa-star"></i>
                          <% end %>
                          <% (5 - review.rating).times do %>
                            <i class="fa-regular fa-star"></i>
                          <% end %>
                        </span>
                      </p>
                      <small><%= review.created_at.strftime('%d/%m/%Y') %></small>
                    </div>
                  </div>
                </div>
            <% end %>
          </div>
          <% end %>
        <% else %>
          <div>
            <p>Aún no tienes reviews</p>
          </div>
        <% end %>
      </div>
      <hr/>
      <div class="travels">
        <p class="title">Viajes de <%= @user.first_name %></p>
        <div class="row mt-4 mb-5">
          <% @plans.each do |plan| %>
              <div class="col-4 d-flex align-items-stretch">
            <%= link_to plan_path(plan), class: "" do %>
                <div class="card plan-card profile-plans shadow h-100">
                  <% if plan.photos.attached? %>
                    <%= cl_image_tag plan.photos.first.key, height: 300, width: 450, crop: :fill, class: 'img-fluid' %>
                  <% else %>
                    <%= image_tag "sinimagen.jpg", height: 300, width: 450, crop: :fill, class: 'img-fluid' %>
                  <% end %>
                  <div class="card-body d-flex flex-column justify-content-between">
                    <h5 class="card-title"><%= plan.name %></h5>
                    <p class="description text-start"><%= plan.description %></p>
                  </div>
                </div>
            <% end %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reviews/my_reviews.html.erb
<div id="myReviews" class="container mt-5" data-controller="edit-review">
  <div class="video-header">
    <div class="banner">
      <video autoplay loop muted>
        <source src="<%= asset_path('reviews.mp4') %>" type="video/mp4">
        Your browser does not support the video tag.
      </video>
      <div class="header-text d-flex justify-content-center text-center">
        <h1 class="bolder">Mis Reviews</h1>
      </div>
    </div>
  </div>

  <% if flash[:notice] %>
    <div class="p-3 mb-2 rounded text-white <%= flash[:notice] ? 'bg-success' : 'bg-danger' %>">
      <strong>
        <span>
          <i class="fa-solid <%= flash[:notice] ? 'fa-check' : 'fa-exclamation-triangle' %>"></i>
          <%= flash[:notice] %>
        </span>
      </strong>
    </div>
  <% end %>


  <div class="row">
    <div class="col-3">
      <div class="card info-profile d-flex flex-row">
        <div class="image">
          <% if @user.photo.attached? %>
            <%= cl_image_tag @user.photo.key, height: 104, width: 104, crop: :fill, class: 'img-fluid' %>
          <% else %>
            <%= image_tag "sinimagen.jpg", height: 104, width: 104, class: 'img-fluid' %>
          <% end %>
          <p class="name"><%= "#{@user.first_name} #{@user.last_name}" %></p>
          <p>TripMater</p>
        </div>
      </div>
    </div>

    <div class="col-9">
      <%= link_to my_travels_path, class: 'd-flex align-items-center back' do %>
        <button class="btn btn-primary me-2"><i class="fa-solid fa-arrow-left"></i></button>
        Volver a mis solicitudes
      <% end %>

      <div class="row d-flex justify-content-between">
        <% @reviews.each do |review| %>
          <div class="col-6 col-card">
            <div class="review-card shadow h-100 d-flex flex-column">
              <div class="review-details flex-grow-1">
                <div class="d-flex align-items-center user">
                  <div class="d-flex align-items-center flex-grow-1">
                    <div class="user-image">
                      <% if review.user.photo.attached? %>
                        <%= cl_image_tag review.user.photo.key, height: 60, width: 60, crop: :fill, class: 'img-fluid rounded-circle' %>
                      <% else %>
                        <%= image_tag "sinimagen.jpg", height: 60, width: 60, class: 'img-fluid rounded-circle' %>
                      <% end %>
                    </div>
                    <p><%= "#{review.travel.plan.user.first_name} #{review.travel.plan.user.last_name}" %></p>
                  </div>
                  <p class="stars">
                    <span>
                      <% review.rating.times do %>
                        <i class="fa-solid fa-star"></i>
                      <% end %>
                      <% (5 - review.rating).times do %>
                        <i class="fa-regular fa-star"></i>
                      <% end %>
                    </span>
                  </p>
                </div>
                <p class="card-text">
                  <i class="bi bi-globe-americas"></i> <strong class="me-2">Viaje realizado: </strong> <%= review.travel.plan.name %>
                </p>
                <div class="review">
                  <p class="card-text"><i class="bi bi-chat-quote"></i> <strong>Comentario:</strong></p>
                  <div class="review-text">
                    <p class="title"><%= review.title %></p>
                    <div class="comment"><%= raw review.comment %></div>
                  </div>
                </div>
              </div>
              <% if @current_user == review.user %>
              <div class="mt-auto text-end">
                <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editReviewModal" data-action="click->edit-review#open" data-review-id="<%= review.id %>">
                  <i class="fa-regular fa-pen-to-square"></i>
                </button>
                <%= link_to review_path(review) || my_reviews_path, class: 'btn btn-primary', data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
                  <i class="bi bi-trash3"></i>
                <% end %>
              </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="modal fade" id="editReviewModal" tabindex="-1" aria-labelledby="editReviewModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="editReviewModalLabel">Editar Reseña</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" data-edit-review-target="form">
          <div class="text-center">
            <div class="spinner-border" role="status">
              <span class="visually-hidden">Cargando...</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/reviews/new.html.erb
<div id="newReview" class="container body mt-5">
  <div class="row">
    <div class="col-5">
      <div class="travel card plan-card shadow h-100">
        <% if @travel.plan.photos.attached? %>
          <%= cl_image_tag @travel.plan.photos.first.key, height: 300, width: 450, crop: :fill, class: 'img-fluid' %>
        <% else %>
          <%= image_tag "sinimagen.jpg", height: 300, width: 450, crop: :fill, class: 'img-fluid' %>
        <% end %>
        <div class="card-body d-flex flex-column justify-content-between">
          <h5 class="card-title"><%= @travel.plan.name %></h5>
          <p class="description text-start"><%= @travel.plan.description %></p>
          <p class="card-text">
            <i class="fa-regular fa-clock me-2"></i>
            <%= (@travel.plan.end_date - @travel.plan.start_date).to_i %> Noches,
            <%= (@travel.plan.end_date - @travel.plan.start_date).to_i + 1 %> Días
          </p>
          <p class="card-text">
          <i class="fa-regular fa-calendar me-2"></i> Fecha de partida: <%= @travel.plan.start_date.strftime('%d/%m/%Y') %>
          </p>
          <p class="card-text">
            <i class="fa-solid fa-user-group me-2"></i> <%= @travel.plan.travelers_quantity %> viajeros
          </p>
          <div class="card-text flex-column align-items-start justify-content-center">
            <p class="my-2"><strong>Creador del viaje</strong></p>
            <div class="d-flex card-user">
              <% if @travel.plan.user.photo.attached? %>
                <%= cl_image_tag @travel.plan.user.photo.key, height: 48, width: 48, crop: :fill, class: 'avatar img-fluid rounded-circle' %>
              <% else %>
                <%= image_tag "sinimagen.jpg", height: 48, width: 48, crop: :fill, class: 'avatar img-fluid rounded-circle' %>
              <% end %>
              <div>
                <p><strong><%= @travel.plan.user.first_name %></strong></p>
                <p class="traveler">Viajera</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-7 form-section" data-controller="new-review">
      <h2>¿Cómo te fue en tu aventura? Deja tu reseña</h2>
      <%= render 'form', travel: @travel, review: @review %>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<div id="editReview" class="container mt-5 body">
  <div id="flash">
    <% if flash[:notice] %>
      <div class="notice p-3 mb-2 bg-success rounded text-white">
        <strong><span><i class="fa-solid fa-check"></i> Successful.</span></strong>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-5">
      <%= render partial: 'card_travel', locals: { travel: @review.travel } %>
    </div>
    <div class="col-7">
      <div>
        <%= link_to my_reviews_path, class: 'btn btn-dark mb-3' do %>
            <i class="fa-solid fa-arrow-left"></i>
        <% end %>
      </div>
      <div class="review">
        <div class="review-details">
          <h1><%= @review.title %></h1>
          <p class="text-info mb-2">
            <span>
              <% @review.rating.times do %>
                <i class="fa-solid fa-star"></i>
              <% end %>
              <% (5 - @review.rating).times do %>
                <i class="fa-regular fa-star"></i>
              <% end %>
            </span>
            </p>
          <% if @current_user != @review.user %>
            <p><i><%= "#{@review.user.first_name} #{@review.user.last_name}" %></i></p>
          <% end %>
          <p class="mb-4 bg-white rounded shadow p-3"><i class="fa-solid fa-quote-left"></i> <%=raw @review.comment %></p>
        </div>
      </div>
      <% if @current_user == @review.user %>
        <div class="buttons">
          <%= link_to edit_review_path(@review), class: 'btn btn-primary' do %>
            Editar
          <% end %>
          <%= link_to review_path(@review) || my_reviews_path, class: 'btn btn-primary ms-2', data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
            Eliminar
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>