config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get 'messages', to: 'messages#index'
  get 'messages/:id', to: 'messages#show'
  # plans
  get 'my_plans', to: 'plans#my_plans', as: :my_plans
  resources :plans do
    resources :travels, only: %i[create]
    resources :messages, only: %i[new create]
  end
  # patch 'plans/:id/travels/', to: 'travels#rejected'
  # travels
  get 'my_requests', to: 'travels#my_requests', as: :my_requests
  get 'my_travels', to: 'travels#my_travels', as: :my_travels
  get 'my_reviews', to: 'reviews#my_reviews', as: :my_reviews

  # Reviews routes
  resources :travels, except: %i[new create] do
    resources :reviews, only: %i[new create]
  end

  resources :travels, only: [] do
    member do
      patch :mark_as_viewed
    end
  end

  resources :users do
    resources :reviews, only: %i[index show]
  end

  resources :reviews, only: %i[index edit update destroy]
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  has_many :travels, dependent: :destroy
  has_many_attached :photos
  has_many :messages
  has_one_attached :photo

  DEPARTAMENTS = [
    'Amazonas', 'Áncash', 'Apurímac', 'Arequipa', 'Ayacucho', 'Cajamarca',
    'Callao', 'Cusco', 'Huancavelica', 'Huánuco', 'Ica', 'Junín', 'La Libertad',
    'Lambayeque', 'Lima', 'Loreto', 'Madre de Dios', 'Moquegua', 'Pasco', 'Piura',
    'Puno', 'San Martín', 'Tacna', 'Tumbes', 'Ucayali'
  ]

  geocoded_by :start_point
  after_validation :geocode, if: :will_save_change_to_start_point?

  validates :name, :description, :location, :travelers_quantity, :start_date, :end_date, :start_point, presence: true
  validates :departament, inclusion: { in: DEPARTAMENTS, message: "%{value} no es un departamento válido" }
  validate :start_date_cannot_be_in_the_past
  validate :end_date_cannot_be_in_the_past

  private

  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "No puede ser en el pasado")
    end
  end

  def end_date_cannot_be_in_the_past
    if end_date.present? && end_date < Date.today && end_date < start_date
      errors.add(:end_date, "La fecha de retorno no puede ser antes del inicio")
    end
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :set_travels, only: %i[show]

  def index
    if current_user
      if params[:date].present?
        @plans = Plan.where(start_date: params[:date]).where.not(user_id: current_user.id)
      else
        @plans = Plan.where.not(user_id: current_user.id)
      end
    else
      if params[:date].present?
        @plans = Plan.where(start_date: params[:date])
      else
        @plans = Plan.all
      end
    end
  end

  def new
    @departaments = Plan::DEPARTAMENTS
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    @plan.user = current_user
    @plan.save!
    redirect_to my_plans_path, notice: 'success'
    # if @plan.save
    #   redirect_to my_plans_path, notice: 'Plan creado exitosamente.'
    # else
    #   respond_to do |format|
    #     format.html { render :new }
    #     format.json { render json: { errors: @plan.errors.full_messages }, status: :unprocessable_entity }
    #   end
    # end
  end

  def show
    @marker = { lat: @plan.latitude,
              lng: @plan.longitude,
              info_window_html:
              render_to_string(partial: "info_window", locals: {plan: @plan})
            }
    @ticket_available = available_tickets(@travels, @plan).positive?
    @available = available_tickets(@travels, @plan)
    @applied = applied_plan?(@plan) if current_user
  end

  def edit
    @departament = Plan::DEPARTAMENTS
  end

  def update
    @plan.update(plan_params)
    redirect_to plan_path(@plan), notice: 'Plan actualizado exitosamente.'
  end

  def destroy
    @plan.destroy
    redirect_to my_plans_path, status: :see_other
  end

  def my_plans
    @my_plans = Plan.where(user: current_user)
  end

  private

  def plan_params
    params.require(:plan).permit(:name, :description, :travelers_quantity, :location, :start_date, :end_date, :departament, :start_point, :photo, photos: [] )
  end

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def set_travels
    @travels = Travel.where(plan_id: @plan.id)
  end

  def available_tickets(travels, plan)
    num_acepted_travels = travels.where(status: 'aceptado').count
    travelers_quantity = plan.travelers_quantity

    available = travelers_quantity - num_acepted_travels
    return available
  end

  def applied_plan?(plan)
    current_user.travels.where(plan_id: plan.id).exists?
  end
end

app/views/plans/_form.html.erb
<div id="formCreatePlan" data-controller="new-plan">
  <div class="row w-100 align-items-center">
    <div class="col-6 text-center">
      <%= image_tag "https://storage.googleapis.com/gx-global-cms/mkt/4d292b5f-53b8-446e-9258-b518df72beb8.png", class: "image mx-auto" %>
    </div>
    <div class="col-6">
      <div class="card-form">
        <div class="card-body">
          <%= simple_form_for(@plan, html: { id: 'multi-step-form', class: 'needs-validation' }) do |f| %>
            <!-- Pasos -->
            <ul class="steps nav nav-pills mb-4" id="step-tabs">
              <li class="nav-item">
                <div class="nav-link step-item active" id="step1" data-step="0">
                  <div class="step-number">1</div>
                </div>
                <div class="step-label">Información Básica</div>
              </li>
              <li class="nav-item">
                <div class="nav-link step-item" id="step2" data-step="1">
                  <div class="step-number">2</div>
                </div>
                <div class="step-label">Detalles del Viaje</div>
              </li>
              <li class="nav-item">
                <div class="nav-link step-item" id="step3" data-step="2">
                  <div class="step-number">3</div>
                </div>
                <div class="step-label">Fotos</div>
              </li>
            </ul>

            <div id="form-step-1" class="form-step" data-new-plan-target="step">
              <%= f.input :name, label: 'Nombre del plan', required: true, input_html: { class: 'form-control required-input' } %>
              <%= f.input :description, label: 'Descripción', required: true, input_html: { class: 'form-control required-input' } %>
              <%= f.input :location, label: 'Lugares a visitar', as: :text, required: true, input_html: { class: 'form-control required-input rich-editor', 'data-new-plan-target': 'editor', 'data-richeditor': 'rich-editor' } %>
              <div class="text-center mt-4"><button type="button" class="btn btn-secondary btn-md next-step" data-action="click->new-plan#nextStep">Siguiente</button></div>
            </div>
            <div id="form-step-2" class="form-step d-none" data-new-plan-target="step">
              <%= f.input :travelers_quantity, label: 'Cantidad de Viajeros', input_html: { class: 'form-control required-input' } %>

              <%= f.input :start_date, as: :string, label: 'Fecha de Inicio', input_html: { class: 'form-control required-input', 'data-new-plan-target': 'startDate'} %>

              <%= f.input :end_date, as: :string, label: 'Fecha de Fin', input_html: { class: 'form-control required-input', 'data-new-plan-target': 'endDate'} %>

              <div class="form-group mb-3">
                <label class="mb-2 fw-bolder">Departamento *</label>
                <%= f.text_field :departament, list: 'departments_list', class: 'form-control', required: true, placeholder: 'Selecciona un departamento' %>
                <datalist id="departments_list">
                  <% departaments.each do |department| %>
                    <option value="<%= department %>"></option>
                  <% end %>
                </datalist>
              </div>

              <%= f.input :start_point,
                input_html: {
                  class: "d-none",
                  data: {
                    start_point_autocomplete_target: "startPoint"
                  }
                },
                wrapper_html: {
                  data: {
                    controller: "start-point-autocomplete",
                    start_point_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]
                  }
                }
              %>

              <div class="text-center">
                <button type="button" class="btn btn-outline-secondary btn-md prev-step me-3" data-action="click->new-plan#prevStep">Anterior</button>
                <button type="button" class="btn btn-secondary btn-md next-step" data-action="click->new-plan#nextStep">Siguiente</button>
              </div>
            </div>


            <div id="form-step-3" class="form-step d-none" data-new-plan-target="step">
              <div>
                <h4>Icono</h4>
                <%= f.input :photo, as: :file, label: false %>
              </div>

              <h4>Fotos</h4>
              <% if @plan.photos.attached? %>
                  <% @plan.photos.each do |photo| %>
                  <div id="photo-previews" data-new-plan-target="preview" class="mb-3 d-inline-block">
                    <%= cl_image_tag photo.key, class: 'photo-thumbnail' %>
                  </div>
                    <%= f.hidden_field :photos, multiple: true, value: photo.signed_id %>
                  <% end %>
                  <%= f.input :photos,
                              as: :file,
                              hint: "Agrega más fotos",
                              input_html: {
                                multiple: true,
                                class: 'form-control',
                                'data-new-plan-target': 'input'
                              },
                              label: false %>
              <% else %>
                <div id="photo-previews" data-new-plan-target="preview" class="mb-3"></div>
                <%= f.input :photos, as: :file, input_html: { multiple: true, class: 'form-control', 'data-new-plan-target': 'input' }, label: false %>
              <% end %>

              <div class="text-center">
                <button type="button" class="btn btn-outline-secondary btn-md prev-step me-3" data-action="click->new-plan#prevStep">Anterior</button>
                <%= f.button :submit, "Enviar", class: 'btn btn-secondary btn-md' %>
              </div>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/plans/_info_window.html.erb
<div class="popup-content">
  <h2 class="popup-title"><%= @plan.name %></h2>
  <p class="popup-description"><%= @plan.description %></p>
  <p class="popup-dates">
    <i class="fas fa-calendar-day"></i>
    <span>Inicio: <%= @plan.start_date %></span>
  </p>
  <p class="popup-dates">
    <i class="fas fa-calendar-check"></i>
    <span>Fin: <%= @plan.end_date %></span>
  </p>
  <p class="popup-travelers">
    <i class="fas fa-users"></i>
    <span><%= @plan.travelers_quantity %> viajeros</span>
  </p>
</div>

app/views/plans/edit.html.erb
<div class="container mt-5">
  <%= render 'form', plan: @plan %>
</div>

app/views/plans/index.html.erb
<div id="plans" class="container mt-5">
  <div class="plans-header">
      <div class="banner">
        <video autoplay loop muted>
          <source src="<%= asset_path('plans.mp4') %>" type="video/mp4">
          Your browser does not support the video tag.
        </video>
        <div class="header-text container content d-flex justify-content-center text-center">
          <div>
            <h1 class="bolder">Planes de viaje.</h1>
          </div>
        </div>
      </div>
  </div>
  <div class="container">
    <div class="row mt-4 mb-5">
      <div class="col-12">
        <div class="search-box d-flex align-items-center justify-content-between p-3 bg-light">
          <form id="date-filter-form" data-controller="flatpickr" data-flatpickr-target="form" class="d-flex flex-grow-1">
            <div class="form-group me-3">
              <input type="text" id="date-picker" data-flatpickr-target="date" class="form-control form-control-lg" placeholder="Seleccionar fecha"
              value="<%= params[:date] %>"/>
            </div>
            <button type="submit" class="btn btn-secondary btn-md" data-action="flatpickr#search">Buscar</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-3 px-0" data-controller="map-filter">
      <div class="map">
        <p class="title"><i class="fa-solid fa-magnifying-glass"></i> Buscar en el mapa</p>
        <div>
          <p class="department-name"></p>
        </div>
        <%= render "shared/map" %>
        <div data-map-filter-target="tooltip" style="display: none; position: absolute; background: #333; color: #fff; padding: 5px; border-radius: 3px;"></div>
      </div>
    </div>

    <div class="col-9 container-cards">
      <% if @plans.empty? %>
        <p class="d-flex flex-column align-items-center"><i class="bi bi-emoji-tear fs-1"></i>No hay planes en este momento.</p>
      <% else %>
        <div class="row mt-4 mb-5">
          <% @plans.each do |plan| %>
            <% num_accepted = Travel.where(plan_id: plan.id, status: 'aceptado').count %>
            <% available = plan.travelers_quantity - num_accepted %>
            <% if available > 0 && plan.start_date > Date.today %>
              <div class="col-4 d-flex align-items-stretch mb-4">
                <div class="card plan-card shadow h-100" data-department=<%=plan.departament%>>
                  <% if plan.photos.attached? %>
                    <%= cl_image_tag plan.photos.first.key, height: 300, width: 450, crop: :fill, class: 'img-fluid' %>
                  <% else %>
                    <%= image_tag "sinimagen.jpg", height: 300, width: 450, crop: :fill, class: 'img-fluid' %>
                  <% end %>
                  <div class="card-body d-flex flex-column">
                    <div class="flex-grow-1">
                      <h5 class="card-title"><%= plan.name %></h5>
                      <p class="description text-start"><%= plan.description %></p>
                      <p class="card-text">
                        <i class="bi bi-geo-alt me-2"></i> <%= plan.departament %>
                      </p>
                      <p class="card-text">
                        <i class="fa-regular fa-clock me-2"></i>
                        <%= (plan.end_date - plan.start_date).to_i %> Noches,
                        <%= (plan.end_date - plan.start_date).to_i + 1 %> Días
                      </p>
                      <p class="card-text">
                      <i class="fa-regular fa-calendar me-2"></i> Fecha de partida: <%= plan.start_date.strftime('%d/%m/%Y') %>
                      </p>
                      <p class="card-text">
                        <i class="fa-solid fa-user-group me-2"></i> <%= plan.travelers_quantity %> <%= state = plan.travelers_quantity == 1 ? 'viajero' : 'viajeros' %>
                      </p>
                      <p class="card-text">
                        <i class="fa-solid fa-ticket me-2"></i> <%= available %> <%= state = available == 1 ? 'disponible' : 'disponibles' %>
                      </p>
                    </div>
                    <%= link_to "Ver más", plan_path(plan), class: "btn btn-secondary btn-sm mt-2"%>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <a href="#" data-controller="scroll" data-scroll-target="scrollButton" class="scroll-to-top">
    <i class="fa fa-arrow-up"></i>
  </a>
</div>

app/views/plans/my_plans.html.erb
<div id="myTravels" class="container body mt-5" data-controller="my-plans">
  <div class="header">
    <div class="banner">
      <video autoplay loop muted>
        <source src="<%= asset_path('my_travels.mp4') %>" type="video/mp4">
        Your browser does not support the video tag.
      </video>
      <div class="header-text container content d-flex justify-content-center text-center">
        <div>
          <h1 class="bolder">Mis Viajes</h1>
        </div>
      </div>
    </div>
  </div>
  <% if flash[:notice] %>
      <div class="notice p-3 mb-2 bg-success rounded text-white">
        <strong><span><i class="fa-solid fa-check"></i> Plan deleted succesfully.</span></strong>
      </div>
    <% end %>
  <div class="row">
    <% @my_plans.each do |plan| %>
      <div class="col-12 col-lg-6 carousel-card">
        <div class="card plan-card travel-card shadow h-100">
          <div class="row">
            <div class="col-7">
              <div class="card-body d-flex flex-column h-100">
                <div class="flex-grow-1">
                  <h4><%= plan.name %></h4>
                  <p class="description text-start"><%= plan.description %></p>
                  <p class="card-text">
                    <i class="fa-solid fa-location-dot me-2"></i><%= plan.departament %>
                  </p>
                  <p class="card-text">
                  <i class="fa-regular fa-calendar me-2"></i> Fecha de partida: <%= plan.start_date.strftime('%d/%m/%Y') %>
                  </p>
                  <p class="card-text">
                    <i class="fa-solid fa-user-group me-2"></i> <%= plan.travelers_quantity %> viajeros
                  </p>
                </div>
                <div class="d-flex flex-column gap-3 align-items-end mt-3">
                  <div class="d-flex gap-2 justify-content-end align-items-end">
                    <%= link_to plan_path(plan), class: "btn btn-primary" do %>
                      <i class="fa-regular fa-eye"></i>

                    <% user_plan = plan.user_id %>
                    <% if user_plan == current_user.id && plan.travels.where(status: "aceptado").exists? %>
                        <%#= link_to "Iniciar Conversación", new_plan_message_path(plan), class: "btn btn-primary btn-reserve" %>
                        <%= link_to new_plan_message_path(plan), class: "btn btn-primary btn-reserve" do %>
                          <i class="fa-regular fa-comment"></i>
                        <% end %>
                    <% end %>
                    <% end %>
                    <%= link_to edit_plan_path(plan), class: "btn btn-primary" do %>
                      <i class="fa-solid fa-pen-to-square"></i>
                    <% end %>
                    <% unless plan.travels.where(status: "aceptado").exists? %>
                      <%= link_to plan_path(plan),data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" do %>
                        <i class="fa-solid fa-trash-can"></i>
                      <% end %>
                    <% end %>
                  </div>
                    <%= link_to my_requests_path(query: { plan_id: plan }), class: "btn btn-primary" do %>
                      Ver solicitudes
                    <% end %>

                </div>
              </div>
            </div>
            <div class="col-5 h-100">
            <% if plan.photos.attached? %>
              <div class="carousel-plan splide h-100" aria-label="My Awesome Gallery">
                <div class="splide__track h-100">
                  <ul class="splide__list">
                    <% plan.photos.each do |photo| %>
                      <li class="splide__slide">
                        <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            <% else %>
              <%= image_tag "sinimagen.jpg", height: 300, width: 250, crop: :fill %>
            <%end%>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/plans/new.html.erb
<div class="container mt-5">
  <%= render 'form', plan: @plan %>
</div>

app/views/plans/show.html.erb
<div id="showPlan" data-controller="show-plan">
  <div id="flash">
    <% if flash[:notice] == 'success' %>
      <div class="notice p-3 mb-2 bg-success rounded text-white">
        <strong><span><i class="fa-solid fa-check"></i> Plan creado exitosamente.</span></strong>
      </div>
    <% end %>
  </div>
  <div class="container mt-5">
    <div>
      <%= link_to plans_path, class: 'btn btn-secondary mb-3' do %>
          <i class="fa-solid fa-arrow-left"></i>
      <% end %>
    </div>
    <div class="row">
      <div class="col-12 col-md-5">
        <p class="title-header"><%= @plan.name %></p>
        <hr/>
        <div class="tripmate">
          <%= link_to user_reviews_path(@plan.user), class:"d-flex align-items-center" do %>
            <div class="me-3">
              <% if @plan.user.photo.attached? %>
                <%= cl_image_tag @plan.user.photo.key, height: 40, width: 40, crop: :fill, class: 'img-fluid' %>
              <% else %>
                <%= image_tag "sinimagen.jpg", height: 40, width: 40, crop: :fill, class: 'img-fluid' %>
              <% end %>
            </div>
            <div class="user">
              <p class="name">Viaja con <%= @plan.user.first_name %></p>
              <p class="description">
                Nuevo viajero
              </p>
            </div>
          <% end %>
        </div>
        <hr/>
        <p class="mb-2"><%= @plan.description %></p>
        <hr/>
          <div class="description-plan">
            <p class="title"><i class="fa-solid fa-plane me-2"></i>Lugares a visitar:</p>
            <%=raw @plan.location%>
          </div>
        <hr>
          <div id="tripmates">
            <p class="title">
                <i class="fa-solid fa-user-group"></i>
              Tripmates
            </h4>
            <div class="tripmates">
              <% if @travels %>
                <% @travels.each do |travel| %>
                  <% if travel.status == 'aceptado' %>
                    <div class="tripmate">
                      <%= link_to user_reviews_path(travel.user) do %>
                        <% if travel.user.photo.attached? %>
                          <%= cl_image_tag travel.user.photo.key, height: 50, width: 50, crop: :fill, alt: travel.user.first_name %>
                        <% else %>
                          <%= image_tag 'sinimagen.jpg', height: 50, width: 50, alt: travel.user.first_name %>
                        <% end %>
                        <p>
                          <%= travel.user.first_name %>
                        </p>
                      <% end %>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
            </div>

            <div>

            </div>

          </div>
        <div class="d-flex gap-2">
          <%#= link_to 'Enviar solicitud', plan_travels_path, class: "btn btn-primary" %>
          <%#= button_to 'Enviar solicitud', plan_travels_path, method: :post, params {key: value}%>
        </div>
      </div>
      <div class="col-12 col-md-7">
        <div class="container-carousel">
          <section id="main-carousel" class="splide" aria-label="My Awesome Gallery">
            <div class="splide__track">
              <ul class="splide__list">
                <% @plan.photos.each do |photo| %>
                  <li class="splide__slide">
                    <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
                  </li>
                <% end %>
              </ul>
            </div>
          </section>
          <ul id="thumbnails" class="thumbnails">
            <% @plan.photos.each do |photo| %>
              <li class="thumbnail">
                <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="detail-card">
          <div class="departament">
            <i class="fa-solid fa-location-dot"></i>
            <%= @plan.departament  %>
          </div>

          <div class="date-picker">
            <div class="date-section">
              <div class="date-label">LLEGADA</div>
              <div class="date-value"><%= @plan.start_date.strftime('%d/%m/%Y') %></div>
            </div>
            <div class="date-section">
              <div class="date-label">SALIDA</div>
              <div class="date-value"><%= @plan.end_date  .strftime('%d/%m/%Y') %></div>
            </div>
          </div>

          <div class="guest-select">
            <div class="date-section">
              <div class="guest-label">VIAJEROS</div>
              <div class="guest-value"><%= @plan.travelers_quantity%> viajeros</div>
            </div>
            <div class="date-section">
              <div class="guest-label">DISPONIBLES</div>
              <div class="guest-value">
                <% if @available == 0 %>
                  <span class='text-bg-primary text-white'>&nbsp;Completado&nbsp;</span>
                <% else %>
                <%= @available %> tickets
                <% end %>
              </div>
            </div>
          </div>
          <% if user_signed_in? %>
              <% plan_users_accepted = @plan.travels.where(status: "aceptado").pluck(:user_id) %>
              <% user_plan = @plan.user_id %>
              <% if plan_users_accepted.include?(current_user.id) || user_plan == current_user.id %>
                  <%= link_to "Iniciar Conversación", new_plan_message_path(@plan), class: "btn btn-primary btn-reserve" %>
              <% end %>
            <% if current_user != @plan.user %>
              <% if @applied %>
                <%= button_to 'Ya lo solicitaste', "#", method: :post, class: "btn btn-primary btn-reserve", disabled: true %>
              <% elsif @ticket_available %>
                <%= button_to 'Solicitar', plan_travels_path(@plan), method: :post, class: "btn btn-primary btn-reserve", data:{turbo:false} %>
              <% else %>
                <%= button_to 'Agotado', plan_travels_path(@plan), class: "btn btn-primary btn-reserve", disabled: true %>
              <% end %>
            <% end %>
          <% else %>
            <%= button_to 'Solicitar', new_user_session_path, class: "btn btn-primary btn-reserve" %>
          <% end %>

        </div>

      </div>

        <div class="container mt-4">
          <div style="width: 100%; height: 600px;"
          data-controller="start-point"
          data-start-point-marker-value="<%= @marker.to_json %>"

          data-start-point-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
  </div>
</div>